aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn run bootstrap
      - run: yarn test
  deploy-website:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "nicolaslopezj@users.noreply.github.com"
            git config --global user.name "Nicolás López"
            echo "machine github.com login nicolaslopezj password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=nicolaslopezj yarn run publish-gh-pages
workflows:
  version: 2
  deploy_website:
    jobs:
      - deploy-website:
          filters: *filter-only-master
  test:
    jobs:
      - test
